app/accounts/urls.py
from django.urls import path
from .views import LoginView, LoggedOut, UserRegisterView, MyProfileView, UserUpdateView

app_name="accounts"
urlpatterns=[
    path("login/", LoginView.as_view(), name="login") ,
    path("logout/", LoggedOut.as_view(), name="logout"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("profiledata/", MyProfileView.as_view(), name="profile"),
    path("update/", UserUpdateView.as_view(), name = "update")
]

app/home/urls.py
from django.urls import path
from .views import IndexView, ContactUs, Aboutt, detail, category_list, NewCreateView, NewUpdateView, DeleteView, deletepage, SearchView

app_name="home"

urlpatterns=[

    path("", IndexView.as_view(), name="home"),
    path("contact/", ContactUs.as_view(), name="contact"),
    path('about/', Aboutt.as_view(), name="about"),
    path("detail/<int:id>/", detail.as_view(), name="detail") ,
    path("category_list/<int:id>/", category_list.as_view() , name="category_list") ,
    path("newcreate/", NewCreateView.as_view(), name="newcreate"),
    path("newupdate/<int:id>/", NewUpdateView.as_view(), name="newupdate"),
    path('delete/<int:id>/', DeleteView.as_view(), name='delete'),
    path('deletewarning/<int:id>/', deletepage.as_view(), name='warning_delete'),
    path('search/', SearchView.as_view(), name='search')
    

    

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app.accounts.urls')),
    path('', include('app.home.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}



<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap Ecommerce Template" name="keywords">
        <meta content="Bootstrap Ecommerce Template Free Download" name="description">

        <!-- Favicon -->
        <link href="{% static 'img/mana.svg' %}" rel='icon'>

            
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>
        <!-- Top Header Start -->
        <div class="top-header">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-4">
                        <div class="logo">
                            <a href="/">
                                <img src="{% static 'img/logo.png' %}" alt="Logo">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4">
                        <div class="search">
                            <form method="GET" action="{% url 'home:search' %}">
                                <input type="text" placeholder="Search" name="query">
                                <button type="submit"><i class="fa fa-search"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-4">
                        <div class="social">
                            <a href=" {{ about.twitter }} " ><i class="fab fa-twitter"></i></a>
                            <a href="{{ about.facebook }}"><i class="fab fa-facebook"></i></a>
                            <a href="{{ about.linkedin }}"><i class="fab fa-linkedin"></i></a>
                            <a href="{{ about.instagram }}"><i class="fab fa-instagram"></i></a>
                            <a href="{{ about.youtube }}" target='_blank'><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Top Header End -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
            {{ message }}
            </li>
            {% endfor %}
        </ul>
    {% endif %}

        <!-- Header Start -->
        <div class="header">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav m-auto">
                            {% block menu %}
                            
                            {% endblock menu %}
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Header End -->





        {% block content %}
        {% endblock content %}




        <!-- Footer Start -->
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Tags</h3>

                            {% for i in tags %}

                            <ul>
                                <li><a href="/search/?query={{ i.name }}">{{i.name}}</a></li>
                                
                            </ul>

                            {% endfor  %}

                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Categories</h3>
                            
                            {% for categor in kategoriyalar %}
                                <ul>
                                    <li><a href="{% url 'home:category_list' categor.id %}">{{categor.name}}</a></li>
                                </ul>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker">{{ about.location }}</i></p>
                                <p><i class="fa fa-envelope">{{ about.email }}</i></p>
                                <p><i class="fa fa-phone">{{ about.phone }}</i></p>
                                <div class="social">

                                    <a href=" {{ about.twitter }} " ><i class="fab fa-twitter"></i></a>
                                    <a href="{{ about.facebook }}"><i class="fab fa-facebook"></i></a>
                                    <a href="{{ about.linkedin }}"><i class="fab fa-linkedin"></i></a>
                                    <a href="{{ about.instagram }}"><i class="fab fa-instagram"></i></a>
                                    <a href="{{ about.youtube }}" target='_blank'><i class="fab fa-youtube"></i></a>

                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Newsletter</h3>
                            <div class="newsletter">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed porta dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra inceptos
                                </p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email here">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="https://htmlcodex.com">HTML Codex</a>. All Rights Reserved</p>
                    </div>

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    <div class="col-md-6 template-by">
                        <p>Template By <a href="https://htmlcodex.com">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->


        <!-- Back to Top -->
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>


        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/category_news.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
category news
{% endblock title %}



{% block menu %}
<a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for categor in kategoriyalar %}
        <a href="{% url 'home:category_list' categor.id %}" class="nav-item nav-link ">{{ categor.name }}</a>
    {% endfor %}

        <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
    
{% endblock menu %}


{% block content %}
<div class="container">
    <h1 style="color:blue">{{ ctg.name }}</h1>
    {% for new in categorynew %}
        <a href="{% url 'home:detail' new.id %}"><h1 >{{ new.title }}</h1>
        <img src="{{ new.image.url }}" style="width: 600px; height: 400px; "/>
    </a>
        <br>
        <br>

    {% endfor %}
</div>    
</div>
{% endblock content %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
contact
{% endblock title %}

{% block menu %}
<a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for categor in kategoriyalar %}
        <a href="{% url 'home:category_list' categor.id %}" class="nav-item nav-link">{{categor.name}}</a>
    {% endfor %}

        <a href="{% url 'home:contact' %}" class="nav-item nav-link active">Contact Us</a>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Log out</a>
        <a href="{% url 'home:newcreate' %}" class="nav-item nav-link">Add new</a>

    {% else %}
        <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Log in</a>
    {% endif %}
{% endblock menu %}



{% block content %}      
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Contact</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        
        <!-- Contact Start -->
        <div class="contact">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-4">
                        <div class="form">
                            <form method='POST'>
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <input type="text" class="form-control" name="name" placeholder="Your Name" />
                                    </div>
                                    <div class="form-group col-md-6">
                                        <input type="email" class="form-control" name="email" placeholder="Your Email" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="subject"  placeholder="Subject" />
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" rows="5" name="message" placeholder="Message"></textarea>
                                </div>
                                <div><button class="btn" type="submit">Send Message</button></div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="map">
                            <iframe src="" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="contact-info">
                            <h3>Get in Touch</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In condimentum quam ac mi viverra dictum. In efficitur ipsum diam, at dignissim lorem tempor in. Vivamus tempor hendrerit finibus.
                            </p>
                            <h4><i class="fa fa-map-marker"></i></h4>
                            <h4><i class="fa fa-envelope"></i></h4>
                            <h4><i class="fa fa-phone"></i></h4>
                            <div class="social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook"></i></a>
                                <a href=""><i class="fab fa-linkedin"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                                <a href=""><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
{% endblock content %}  

templates/deletenew.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Delete Page
{% endblock title %}
{% block content %}
    <div class="container">
    <h1>Do you really want to delete this post permanently?... </h1>
    {{ data.title }}
    <br>
    <img src="{{ data.image.url }}" alt="image" style="width: 400px; height: 300px;">
    <br>
    <button type="button" class="btn btn-danger"><a href="{% url 'home:delete' data.id %}">Delete</a></button>
    <button type="button" class="btn btn-info"><a href="{% url 'home:home' %}"> Back </a></button>
    </div>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}  
{% load static %}  
{% block title %}
single-page
{% endblock title %}


{% block menu %}
<a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for categor in kategoriyalar %}
        <a href="{% url 'home:category_list' categor.id %}" class="nav-item nav-link">{{categor.name}}</a>
    {% endfor %}

        <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Log out</a>
        <a href="{% url 'home:newcreate' %}" class="nav-item nav-link">Add new</a>

    {% else %}
        <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Log in</a>
    {% endif %}
{% endblock menu %}




{% block content %}
        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container-fluid">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">News</a></li>
                    <li class="breadcrumb-item active">News details</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        
        
        <!-- Single News Start-->
        <div class="single-news">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8">
                        <div class="sn-img">
                            <img src="{{ data.image.url }}" />
                        </div>
                        <div class="sn-content">
                            {% if user.is_authenticated and user == data.author %}
                                <a href="{% url 'home:warning_delete' data.id %}" class="btn btn-info">Delete</a>
                                <a href="{% url 'home:newupdate' data.id %}" class="btn btn-info">Update</a>
                            {% endif %}
                            <a class="sn-title" href="{% url 'home:detail' data.id %}">{{data.title}}</a>
                            <h5> views : {{ data.views }} </h5>
                            <a class="sn-date" href="{% url 'home:detail' data.id %}"><i class="far fa-clock"></i>{{data.updated_at}}</a>
                            <p>
                                {{ data.body|safe }} 
                            </p>
                            
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="sidebar">
                            <div class="sidebar-widget">
                                <h2><i class="fas fa-align-justify"></i>Category</h2>
                                <div class="category">
                                {% for categ in kategoriyalar %}
                                    <ul class="fa-ul">
                                        <li><span class="fa-li"><i class="far fa-arrow-alt-circle-right"></i></span><a href="{% url 'home:category_list' categ.id %}">{{categ.name}}</a></li>
                                    </ul>
                                {% endfor %}
                                </div>
                            </div>

                            <div class="sidebar-widget">
                                <h2><i class="fas fa-align-justify"></i>Tags</h2>
                                <div class="tags">
                                {% for tag in tags %}
                                    <a href="">{{tag.name}}</a>
                                {% endfor %}  
                                </div>
                            </div>

                            {% if ads_one %}

                            <div class="sidebar-widget">
                                <div class="image">
                                    <a href="{{ ads_one.link }}"><img src="{{ ads_one.image.url }}" alt="Image"></a>
                                </div>
                            </div>
                            {% endif %}


                            <div class="sidebar-widget">
                                <div class="image">
                                    <div class="row">
                                        {% if ads_two %}
                                            {% for ads in ads_two %}
                                                <div class="col-sm-6">
                                                    <a href="{{ ads.link }}"><img src="{{ ads.image.url }}" alt="Image"></a>
                                                </div>
                                            {% endfor %}
                                        {% endif %}

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Single News End-->
{% endblock content %}

templates/new_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Creating New Post 
{% endblock title %}
{% block content %}
    <h1>Please create new post </h1>
    <form method='POST' class="container" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='create'>
        <button type="button" class="btn btn-success"><a href="{% url 'home:home' %}">Back</a></button>
    </form>
    
{% endblock content %}

templates/new_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Creating New Post 
{% endblock title %}
{% block content %}
    <h1>Please update new post </h1>
    <form method='POST' class="container" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='update'>
        <button type="button" class="btn btn-success"><a href="{% url 'home:home' %}">Back</a></button>
    </form>
    
{% endblock content %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Search result page
{% endblock title %}



{% block menu %}
<a href="{% url 'home:home' %}" class="nav-item nav-link">Home</a>
    {% for categor in kategoriyalar %}
        <a href="{% url 'home:category_list' categor.id %}" class="nav-item nav-link {% if categor.id == ctg.id %} active {% endif %}">{{ categor.name }}</a>
    {% endfor %}

        <a href="{% url 'home:contact' %}" class="nav-item nav-link">Contact Us</a>
    
{% endblock menu %}


{% block content %}
<div class="container">
    {% for new in searchnews %}
        <a href="{% url 'home:detail' new.id %}"><h3> {{ new.title }} </h3></a>
        <h3>{{new.body|safe|truncatewords:50|linebreaks}}</h3>
        <img src="{{ new.image.url }}" alt="image" style="width: 600px; height: 400px;">
    {% endfor %}
</div>
{% endblock content %}